apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane
metadata:
  name: {{ include "k0smotroncontrolplane.name" . }}
spec:
  etcd:
    persistence:
      storageClass: {{ .Values.k0smotron.etcd.persistence.storageClass }}
  controllerPlaneFlags:
  - "--enable-cloud-provider=true"
  - "--kubelet-extra-args=--cloud-provider=external"
  - "--disable-components=konnectivity-server"
  k0sConfig:
    apiVersion: k0s.k0sproject.io/v1beta1
    kind: ClusterConfig
    metadata:
      name: k0s
    spec:
      extensions:
        helm:
          repositories:
            - name: openstack
              url: https://kubernetes.github.io/cloud-provider-openstack/
          charts:
            - name: openstack-ccm
              chartname: openstack/openstack-cloud-controller-manager
              version: 2.31.1
              order: 1
              namespace: kube-system
              values: |
                secret:
                  enabled: true
                  name: openstack-cloud-config
                  create: false
                nodeSelector:
                  node-role.kubernetes.io/control-plane: "true"
                tolerations:
                  - key: node.cloudprovider.kubernetes.io/uninitialized
                    value: "true"
                    effect: NoSchedule
                  - key: node-role.kubernetes.io/control-plane
                    effect: NoSchedule
                  - key: node-role.kubernetes.io/master
                    effect: NoSchedule                  
            - name: openstack-csi
              chartname: openstack/openstack-cinder-csi
              version: 2.31.3
              order: 2
              namespace: kube-system
              values: |
                storageClass:
                  enabled: true
                  delete:
                    isDefault: false
                    allowVolumeExpansion: true
                  retain:
                    isDefault: false
                    allowVolumeExpansion: false
                secret:
                  enabled: true
                  name: openstack-cloud-config
                  create: false
                csi:
                  plugin:
                    nodePlugin:
                      kubeletDir: /var/lib/k0s/kubelet                  
      network:
        provider: calico
        calico:
          mode: vxlan                  
  replicas: {{ .Values.controlPlaneNumber }}
  {{- with .Values.k0smotron.service }}
  service:
    {{- toYaml . | nindent 4 }}
  {{- end }}  
  version: {{ .Values.k0s.version | replace "+" "-" }}
