apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackCluster
metadata:
  name: {{ include "cluster.name" . }}
  annotations:
    cluster.x-k8s.io/managed-by: k0smotron
  finalizers:
  - hmc.mirantis.com/cleanup
spec:
  {{- if .Values.apiServerLoadBalancer }}
  apiServerLoadBalancer:
    {{- toYaml .Values.apiServerLoadBalancer | nindent 4 }}
  {{- end }}
  {{- if .Values.bastion.enabled }}
  {{- with .Values.bastion.spec }}
  bastion:
    spec:
      {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- end }}
  {{- if .Values.externalNetwork }}
  externalNetwork:
    {{- toYaml .Values.externalNetwork | nindent 4 }}
  {{- end }}
  {{- if .Values.identityRef }}
  identityRef:
    name: {{ .Values.identityRef.name }}
    cloudName: {{ .Values.identityRef.cloudName }}
    region: {{ .Values.identityRef.region }}
  {{- end }}
  {{- if .Values.managedSecurityGroups }}
  managedSecurityGroups:
    {{- toYaml .Values.managedSecurityGroups | nindent 4 }}
  {{- end }}
  {{- if .Values.router }}
  router:
    {{- toYaml .Values.router | nindent 4 }}
  {{- end }}
  {{- if .Values.subnets }}
  subnets:
    {{- toYaml .Values.subnets | nindent 4 }}
  {{- end }}
